# -*- coding: utf-8 -*-
"""cnnBiLSTM_solarPower.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgE4rYNVJkGcJDprWLv-XNCHrGwX_Tv5
"""

!git clone https://github.com/Bob05757/Renewable-energy-generation-input-feature-variables-analysis

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Dense, LSTM, Conv1D, Dropout, Bidirectional, Multiply,
    Permute, Flatten, RepeatVector, Lambda, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
import pandas as pd
import numpy as np
# Attention Mechanism
def attention_3d_block(inputs, single_attention_vector=False):
    time_steps = tf.keras.backend.int_shape(inputs)[1]
    input_dim = tf.keras.backend.int_shape(inputs)[2]

    a = Permute((2, 1))(inputs)
    a = Dense(time_steps, activation='softmax')(a)

    if single_attention_vector:
        a = GlobalAveragePooling1D()(a)
        a = RepeatVector(input_dim)(a)

    a_probs = Permute((2, 1))(a)
    output_attention_mul = Multiply()([inputs, a_probs])

    return output_attention_mul

# Model function
def attention_model():
    inputs = Input(shape=(TIME_STEPS, INPUT_DIMS))

    x = Conv1D(filters=64, kernel_size=1, activation='relu')(inputs)
    x = Dropout(0.3)(x)

    lstm_out = Bidirectional(LSTM(lstm_units, return_sequences=True))(x)
    lstm_out = Dropout(0.3)(lstm_out)

    attention_mul = attention_3d_block(lstm_out)
    attention_mul = Flatten()(attention_mul)

    output = Dense(1, activation='sigmoid')(attention_mul)
    model = Model(inputs=[inputs], outputs=output)

    return model

# Reverse normalization function
def FNormalizeMult(data, normalize):
    data = np.array(data)
    for i in range(data.shape[1]):
        listlow, listhigh = normalize[i, 0], normalize[i, 1]
        delta = listhigh - listlow
        if delta != 0:
            data[:, i] = data[:, i] * delta + listlow

    return data

# Normalize function
def NormalizeMult(data):
    data = np.array(data)
    normalize = np.zeros((data.shape[1], 2))

    for i in range(data.shape[1]):
        listlow, listhigh = np.percentile(data[:, i], [0, 100])
        normalize[i, 0] = listlow
        normalize[i, 1] = listhigh
        delta = listhigh - listlow
        if delta != 0:
            data[:, i] = (data[:, i] - listlow) / delta

    return data, normalize

# Create dataset function
def create_dataset(dataset, look_back):
    dataX, dataY = [], []
    for i in range(len(dataset) - look_back - 1):
        a = dataset[i:(i + look_back), :]
        dataX.append(a)
        dataY.append(dataset[i + look_back, :])

    return np.array(dataX), np.array(dataY)

# 由renewable ... 项目可知， Atmosphere (hpa) Air_P的相关系数最小，可以剔除。另外，关于时间的东西，可用youtube项目参考,有个三角函数处理
# data = pd.read_csv("/content/Renewable-energy-generation-input-feature-variables-analysis/data_processed/solar_stations/Solarstationsite7(Nominalcapacity-30MW).xlsx")

Dataset_SS_site7 = pd.read_excel(r'/content/Renewable-energy-generation-input-feature-variables-analysis/data_processed/solar_stations/Solar station site 7 (Nominal capacity-30MW).xlsx'
                                ).drop(index=0)

Dataset_SS_site7.columns=['Time','TSI','DNI','GHI','Air_T','Air_P','Air_H','Power(MW)']

Dataset_SS_site7.drop(columns=['Air_P','Air_T', 'Air_H'],inplace=True)

Dataset_SS_site7.head()

"""# 时间转成周期性"""

df = Dataset_SS_site7
df.index = pd.to_datetime(df['Time'], format='%d.%m.%Y %H:%M:%S')

temp = df['Power(MW)']
df['Seconds'] = df.index.map(pd.Timestamp.timestamp)
df

day = 60*60*24
year = 365.2425*day

df['Day sin'] = np.sin(df['Seconds'] * (2* np.pi / day))
df['Day cos'] = np.cos(df['Seconds'] * (2 * np.pi / day))
df['Year sin'] = np.sin(df['Seconds'] * (2 * np.pi / year))
df['Year cos'] = np.cos(df['Seconds'] * (2 * np.pi / year))
df.head()  # TODO 新增的几列计算相关性，可能只有hour是可以采取的

df.drop(columns=['Seconds','Year sin', 'Year cos', 'Time'],inplace=True)
# df.drop(columns=['Time'], inplace=True)
df

# Assuming 'Power(MW)' is the actual column name
power_col = df.pop('Power(MW)')  # Remove 'Power(MW)' column and store it
df.insert(0, 'Power(MW)', power_col)  # Insert it at the beginning (index 0)

df

def df_to_X_y(df, window_size=24):
  df_as_np = df.to_numpy()
  X = []
  y = []
  for i in range(len(df_as_np)-window_size):
    row = [r for r in df_as_np[i:i+window_size]]
    X.append(row)
    label = df_as_np[i+window_size][0]  # 看清楚power是第几列的 需要调整
    y.append(label)
  return np.array(X), np.array(y)

WINDOW_SIZE = 24
X1, y1 = df_to_X_y(df, WINDOW_SIZE)
X1.shape, y1.shape

df = df[3::4]
df

X_train, y_train = X1[:14000], y1[:14000]
X_val, y_val = X1[14000:15760], y1[14000:15760]
X_test, y_test = X1[15760:], y1[15760:]
X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape

temp_training_mean = np.mean(X_train[:, :, 0])
temp_training_std = np.std(X_train[:, :, 0])

def preprocess(X):
  X[:, :, 0] = (X[:, :, 0] - temp_training_mean) / temp_training_std
  return X

preprocess(X_train)
preprocess(X_val)
preprocess(X_test)

INPUT_DIMS = 6
TIME_STEPS = 24
lstm_units = 64

# Normalize data
data, normalize = NormalizeMult(df)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam
model = Sequential()
model.add(InputLayer((WINDOW_SIZE, 6)))
model.add(Conv1D(256, kernel_size=24, activation='relu'))
model.add(Flatten())
model.add(Dense(16, 'relu'))
model.add(Dense(1, 'linear'))
model.summary()

cp = ModelCheckpoint('model_CNN.keras', save_best_only=True)
model.compile(loss=MeanSquaredError(), optimizer=Adam(learning_rate=0.0001), metrics=[RootMeanSquaredError()])

model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=250, callbacks=[cp])

from tensorflow.keras.models import load_model
model = load_model('model_CNN.keras')
train_predictions = model.predict(X_train).flatten()

val_predictions = model.predict(X_val).flatten()

test_predictions = model.predict(X_test).flatten()

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
def evaluate_model(y_true, y_pred, model_name="Model"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    print(f"\n{model_name} Performance Metrics:")
    print(f"MAE: {mae:.4f}")
    print(f"RMSE: {rmse:.4f}")
    print(f"R² Score: {r2:.4f}")

    # 修改MAPE计算，避免除以0的情况
    # 方法1：只计算非零值的MAPE
    non_zero_mask = y_true != 0
    if np.any(non_zero_mask):
        mape = np.mean(np.abs((y_true[non_zero_mask] - y_pred[non_zero_mask]) / y_true[non_zero_mask])) * 100
        print(f"MAPE (excluding zeros): {mape:.2f}%")

    # 方法2：使用SMAPE (对称平均绝对百分比误差)
    smape = np.mean(2 * np.abs(y_pred - y_true) / (np.abs(y_true) + np.abs(y_pred))) * 100
    print(f"SMAPE: {smape:.2f}%")

# Evaluate on all datasets
print("Training Set Evaluation:")
evaluate_model(y_train, model.predict(X_train), "Model (CNN)")

print("\nValidation Set Evaluation:")
evaluate_model(y_val, model.predict(X_val), "Model (CNN)")

print("\nTest Set Evaluation:")
evaluate_model(y_test, model.predict(X_test), "Model (CNN)")

# Visualize actual vs predicted values scatter plot for Power predictions
plt.figure(figsize=(10, 6))
test_predictions = model.predict(X_test)
plt.scatter(y_test[:, 1], test_predictions[:, 1], alpha=0.5)
plt.plot([y_test[:, 1].min(), y_test[:, 1].max()],
         [y_test[:, 1].min(), y_test[:, 1].max()], 'r--', lw=2)
plt.xlabel('Actual Power Values')
plt.ylabel('Predicted Power Values')
plt.title('Model (CNN): Actual vs Predicted Power Values')
plt.tight_layout()
plt.show()















"""# 去掉时间，临时方案"""

data = Dataset_SS_site7.drop(['Time', 'Air_P'], axis=1)
data
# Dataset_SS_site7

INPUT_DIMS = 6
TIME_STEPS = 20
lstm_units = 64

# Normalize data
data, normalize = NormalizeMult(data)

power_data = data[:, 5].reshape(len(data), 1)
power_data

train_X, _ = create_dataset(data, TIME_STEPS)
_, train_Y = create_dataset(power_data, TIME_STEPS)

train_X

model = attention_model()
model.summary()

model.compile(optimizer='adam', loss='mse')
model.fit(train_X, train_Y, epochs=10, batch_size=64, validation_split=0.1)

model.save('model.h5')

from tensorflow.keras.models import load_model
from tensorflow.keras.losses import MeanSquaredError

model = load_model('model.h5', custom_objects={'mse': MeanSquaredError()})
train_Y = train_Y.flatten()  # Or train_Y = train_Y.reshape(-1)
# Generate predictions using the loaded model
train_predictions = model.predict(train_X)
train_results = pd.DataFrame(data={'Train Predictions': train_predictions.flatten(), 'Actuals': train_Y})

train_predictions

import matplotlib.pyplot as plt
plt.plot(train_results['Train Predictions'][:1000])
plt.plot(train_results['Actuals'][:1000])

import matplotlib.pyplot as plt

# Create the plot
plt.plot(train_results['Train Predictions'][:1000], label='Predictions', color='blue')  # Predictions in blue
plt.plot(train_results['Actuals'][:1000], label='Actuals', color='red', linestyle='--')  # Actuals in dashed red

# Remove spines (borders)
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)

# Add labels and legend
plt.xlabel('Data Point Index')  # X-axis label
plt.ylabel('Power (MW)')  # Y-axis label (assuming your data represents power in MW)
plt.legend()  # Show the legend to distinguish lines

# Make the plot a bit larger
plt.figure(figsize=(10, 6))

# Display the plot
plt.show()

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def evaluate_model(y_true, y_pred, model_name="Model"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    print(f"\n{model_name} Performance Metrics:")
    print(f"MAE: {mae:.4f}")
    print(f"RMSE: {rmse:.4f}")
    print(f"R² Score: {r2:.4f}")

evaluate_model(train_Y, train_predictions, "Attention Model")

"""## 导入测试集"""

Dataset_SS_site8 = pd.read_excel(r'/content/Renewable-energy-generation-input-feature-variables-analysis/data_processed/solar_stations/Solar station site 8 (Nominal capacity-30MW).xlsx'
                                ).drop(index=0)

Dataset_SS_site8.columns=['Time','TSI','DNI','GHI','Air_T','Air_P','Air_H','Power(MW)']
test_df = Dataset_SS_site8.drop(['Time', 'Air_P'], axis=1)[:17500]
test_df

test_df['Power(MW)']

test_data, normalize = NormalizeMult(test_df)
test_power_data = test_data[:, 5].reshape(len(test_data), 1)
test_power_data

test_X, _ = create_dataset(test_data, TIME_STEPS)
_, test_Y = create_dataset(test_power_data, TIME_STEPS)

test_predictions = model.predict(test_X)

test_Y = test_Y.flatten()
test_results = pd.DataFrame(data={'Train Predictions': test_predictions.flatten(), 'Actuals': test_Y})

import matplotlib.pyplot as plt
plt.plot(test_results['Train Predictions'][:1000])
plt.plot(test_results['Actuals'][:1000])

# Assuming 'test_results' contains the normalized predictions and 'normalize' contains the normalization parameters
restored_test_results = FNormalizeMult(test_results, normalize)
restored_test_results

restored_df = pd.DataFrame(restored_test_results, columns=['Predicted_Values', 'Actual_Values'])
restored_df

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def evaluate_model(y_true, y_pred, model_name="Model"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    print(f"\n{model_name} Performance Metrics:")
    print(f"MAE: {mae:.4f}")
    print(f"RMSE: {rmse:.4f}")
    print(f"R² Score: {r2:.4f}")

evaluate_model(test_Y, test_predictions, "Attention Model")

test_power_data

plt.figure(figsize=(10, 6))
plt.plot(restored_df['Actual_Values'][:1000], label='Actual Values', color='blue')
plt.plot(restored_df['Predicted_Values'][:1000], label='Predicted Values', color='red')
plt.xlabel('Time')
plt.ylabel('Power (MW)')  # Assuming Power(MW) is the target variable
plt.title('Actual vs Predicted Values')
plt.legend()
plt.show()

y_true = restored_df['Actual_Values']
y_pred = restored_df['Predicted_Values']

# Calculate evaluation metrics
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

# Print the evaluation results
print(f"\nCNN+BiLSTM+Attention Performance Metrics:")
print(f"MAE: {mae:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"R² Score: {r2:.4f}")





"""# 测试FNormalizeMult"""

Dataset_SS_site3 = pd.read_excel(r'/content/Renewable-energy-generation-input-feature-variables-analysis/data_processed/solar_stations/Solar station site 3 (Nominal capacity-30MW).xlsx'
                                ).drop(index=0)
Dataset_SS_site3.head()

Dataset_SS_site3.columns=['Time','TSI','DNI','GHI','Air_P','Air_H','Power(MW)']
df_ = Dataset_SS_site3.drop(['Time', 'Air_P'], axis=1)[:17500]

df_normalize_data, normalize = NormalizeMult(df_)

df_

df_normalize_data

restored_df = FNormalizeMult(df_normalize_data, normalize)
restored_df

FNormalizeMult(test_predictions, normalize)

